# aegis/tests/test_report_export.py
"""Regression tests for AEGIS report export builders."""

from io import BytesIO

import pytest

from core.report_export import (
    build_disclosure_docx,
    build_disclosure_pdf,
    build_docx,
    build_html,
    build_pdf,
)


def _sample_result():
    return {
        "title_block": "Court: Auckland District Court\nCharge: Burglary\nStatute: Crimes Act 1961, s 231",
        "executive_summary": "The prosecution case depends on identification evidence.",
        "charge_and_legislative_framework": "Charge: Burglary\nStatute: Crimes Act 1961, s 231",
        "summary_of_evidence": "1. CCTV footage shows an individual entering the store.\n2. A witness statement describes the suspect.",
        "assessment_of_prosecution_case": "The identification evidence is weak.",
        "evidence_analysis": "CCTV quality is poor and the witness view was brief.",
        "elements_of_the_offence": "1. The defendant entered a building as a trespasser.\n2. The defendant intended to commit a crime inside.",
        "defence_strategies": "Strategy Name: Challenge identification\n**Objective:** Undermine the reliability of the CCTV evidence.",
        "cross_examination_priorities": "1. Confirm the camera angle and lighting conditions.\n2. Establish how long the witness observed the suspect.",
        "disclosure_and_forensic_gaps": "- Chain-of-custody records for seized exhibits\n- Original unedited CCTV footage",
        "instructions_to_counsel_pre_trial": "Obtain the original CCTV footage.",
        "evidentiary_issues_to_raise": "Legal Basis: Evidence Act 2006, s 23\nReliability of the alleged identification.",
        "conclusion": "The defence has a realistic prospect of acquittal.",
        "disclaimer": "This analysis is generated by AI and does not constitute legal advice.",
        "success": True,
    }


def _sample_disclosure_result():
    return {
        "title_block": "Court: Auckland District Court\nCharge: Burglary\nStatute: Crimes Act 1961, s 231",
        "executive_summary": "The prosecution case depends on identification evidence.",
        "charge_analysis": "Charge: Burglary. Statute: Crimes Act 1961, s 231. Elements: entry as trespasser with intent.",
        "summary_of_facts_review": "Summary of facts states entry via rear door. No independent witness confirms intent.",
        "police_conduct_assessment": "No identified breaches.",
        "further_disclosure_required": "1. Original CCTV footage.\n2. Chain-of-custody records.",
        "bail_analysis": "Current bail conditions appear reasonable.",
        "options_and_recommendations": "Option 1: Plead not guilty and challenge identification.",
        "expert_consensus_and_divergence": "All experts agree identification is the key issue.",
        "risk_assessment": "Realistic prospect of acquittal if identification is undermined.",
        "conclusion": "The defence has a realistic prospect of acquittal.",
        "disclaimer": "This analysis is generated by AI and does not constitute legal advice.",
        "success": True,
    }


def test_build_docx_creates_valid_buffer():
    buf = build_docx(_sample_result())
    assert isinstance(buf, BytesIO)
    data = buf.getvalue()
    assert data.startswith(b"PK")
    assert len(data) > 1000


def test_build_docx_contains_all_main_sections():
    from docx import Document

    buf = build_docx(_sample_result())
    doc = Document(buf)
    full_text = "\n".join(p.text for p in doc.paragraphs)
    expected_headings = [
        "1. EXECUTIVE SUMMARY",
        "2. CHARGE AND LEGISLATIVE FRAMEWORK",
        "3. SUMMARY OF EVIDENCE",
        "4. ASSESSMENT OF PROSECUTION CASE",
        "5. EVIDENCE ANALYSIS",
        "6. ELEMENTS THE PROSECUTION MUST PROVE",
        "7. DEFENCE STRATEGIES AND OPTIONS",
        "8. CROSS-EXAMINATION PRIORITIES",
        "9. DISCLOSURE AND FORENSIC GAPS",
        "10. INSTRUCTIONS TO COUNSEL PRE-TRIAL",
        "11. EVIDENTIARY ISSUES TO RAISE",
        "12. CONCLUSION",
    ]
    for heading in expected_headings:
        assert heading in full_text, f"Missing heading: {heading}"


def test_build_html_contains_brand_and_sections():
    html = build_html(_sample_result())
    assert "AEGIS" in html
    assert "EXECUTIVE SUMMARY" in html
    assert "CROSS-EXAMINATION PRIORITIES" in html
    assert "DISCLOSURE AND FORENSIC GAPS" in html
    assert "EVIDENCE ANALYSIS" in html


def test_build_pdf_falls_back_to_fpdf(monkeypatch):
    """When docx2pdf is unavailable, build_pdf must return a valid PDF buffer."""
    import sys
    import core.report_export as re_mod

    # Make docx2pdf unimportable for the duration of the call.
    monkeypatch.setitem(sys.modules, "docx2pdf", None)
    # In case the module was previously imported, remove the cached reference.
    monkeypatch.setattr(re_mod, "convert", None, raising=False)

    buf = build_pdf(_sample_result())
    assert isinstance(buf, BytesIO)
    data = buf.getvalue()
    assert data.startswith(b"%PDF")
    assert len(data) > 1000


def test_build_disclosure_docx_creates_valid_buffer():
    buf = build_disclosure_docx(_sample_disclosure_result())
    assert isinstance(buf, BytesIO)
    data = buf.getvalue()
    assert data.startswith(b"PK")
    assert len(data) > 1000


def test_build_disclosure_docx_contains_disclosure_sections():
    from docx import Document

    buf = build_disclosure_docx(_sample_disclosure_result())
    doc = Document(buf)
    full_text = "\n".join(p.text for p in doc.paragraphs)
    expected_headings = [
        "2. CHARGES REGISTER",
        "3. EVIDENCE AND SUMMARY OF FACTS ASSESSMENT",
        "4. PROCEDURAL BREACHES AND LAW ENFORCEMENT CONDUCT AUDIT",
        "5. FURTHER DISCLOSURE REQUEST",
        "7. ACCUSED OPTIONS AND NEXT STEPS",
    ]
    for heading in expected_headings:
        assert heading in full_text, f"Missing heading: {heading}"


def test_build_disclosure_pdf_falls_back_to_fpdf(monkeypatch):
    """When docx2pdf is unavailable, build_disclosure_pdf must return a valid PDF buffer."""
    import sys
    import core.report_export as re_mod

    monkeypatch.setitem(sys.modules, "docx2pdf", None)
    monkeypatch.setattr(re_mod, "convert", None, raising=False)

    buf = build_disclosure_pdf(_sample_disclosure_result())
    assert isinstance(buf, BytesIO)
    data = buf.getvalue()
    assert data.startswith(b"%PDF")
    assert len(data) > 1000


def test_normalize_legal_basis_does_not_repeat_for_bullets():
    """Bare statute citations inside bullet/numbered lists keep their list marker."""
    from core.report_export import _normalize_legal_basis

    assert _normalize_legal_basis("- Misuse of Drugs Act 1975, s 7(1)(a)") == "- Misuse of Drugs Act 1975, s 7(1)(a)"
    assert _normalize_legal_basis("• Search and Surveillance Act 2012") == "• Search and Surveillance Act 2012"
    assert _normalize_legal_basis("1. Evidence Act 2006, s 23") == "1. Evidence Act 2006, s 23"
    assert (
        _normalize_legal_basis("Legal Basis: Crimes Act 1961, s 231")
        == "Legal Basis: Crimes Act 1961, s 231"
    )
    assert (
        _normalize_legal_basis("Crimes Act 1961, s 231")
        == "Legal Basis: Crimes Act 1961, s 231"
    )


def test_normalize_legal_basis_does_not_prefix_long_paragraphs():
    """Long paragraphs that merely mention a statute are not prefixed with Legal Basis."""
    from core.report_export import _normalize_legal_basis

    para = (
        "Jordan Harper is charged with burglary under the Crimes Act 1961. "
        "The central evidentiary pillar rests on CCTV footage."
    )
    assert "Legal Basis" not in _normalize_legal_basis(para)

    para2 = (
        "The defence will challenge the case under the right to silence "
        "under NZBORA s 24(1)(d)."
    )
    assert "Legal Basis" not in _normalize_legal_basis(para2)


def test_bullet_labels_indent_sub_items():
    """Bullet labels like '• Seized Evidence:' are bold headings with indented sub-bullets."""
    from docx import Document

    result = {
        "title_block": "Court: Test\nCharge: Test",
        "summary_of_evidence": "• Seized Evidence:\n• Container 1\n• Container 2\n• Defendant's Conduct:\n• Act 1\n• Act 2",
        "executive_summary": "",
        "charge_and_legislative_framework": "",
        "assessment_of_prosecution_case": "",
        "evidence_analysis": "",
        "elements_of_the_offence": "",
        "defence_strategies": "",
        "cross_examination_priorities": "",
        "disclosure_and_forensic_gaps": "",
        "instructions_to_counsel_pre_trial": "",
        "evidentiary_issues_to_raise": "",
        "conclusion": "",
        "disclaimer": "",
    }
    buf = build_docx(result)
    doc = Document(buf)

    label_paras = [p for p in doc.paragraphs if p.text.strip().startswith("Seized Evidence") or p.text.strip().startswith("Defendant")]
    sub_paras = [p for p in doc.paragraphs if p.text.strip().startswith("• Container") or p.text.strip().startswith("• Act")]

    assert len(label_paras) == 2
    assert len(sub_paras) == 4

    # Sub-bullets should be indented further than their labels.
    for sub in sub_paras:
        assert sub.paragraph_format.left_indent > label_paras[0].paragraph_format.left_indent
    # Labels should be bold.
    for label in label_paras:
        assert any(run.bold for run in label.runs)


def test_number_weaknesses_converts_bullets_to_continuous_numbers():
    """Weaknesses bullets following a numbered item continue the numbering."""
    from core.agent_swarm import AgentSwarm

    swarm = AgentSwarm.__new__(AgentSwarm)
    text = (
        "1. Chain of Custody Issues: The disclosure does not provide detailed information.\n"
        "• Witness Reliability Concerns: Multiple witnesses are police officers.\n"
        "• Alternative Explanations: The anomalies could be legitimate."
    )
    out = swarm._number_weaknesses(text)
    assert "2. Witness Reliability Concerns:" in out
    assert "3. Alternative Explanations:" in out
    assert "• Witness" not in out


def test_clean_strategy_text_removes_legacy_labels_and_dedupes():
    """Legacy 'Strategy Name:' labels are stripped and duplicate lines collapsed."""
    from core.report_export import _clean_strategy_text

    text = (
        "A.\n"
        "Strategy Name: Challenge the alleged admission\n"
        "Strategy Name: Challenge the alleged admission\n"
        "• 1. Question voluntariness\n"
        "Strength: STRONG\n"
        "B.\n"
        "Strategy Name: Raise reasonable doubt\n"
        "• 1. Question CCTV"
    )
    out = _clean_strategy_text(text)
    assert "Strategy Name" not in out
    assert out.count("Challenge the alleged admission") == 1
    assert "Raise reasonable doubt" in out
