# aegis/tests/test_report_export.py
"""Regression tests for AEGIS report export builders."""

from io import BytesIO

import pytest

from core.report_export import build_docx, build_html, build_pdf


def _sample_result():
    return {
        "title_block": "Court: Auckland District Court\nCharge: Burglary\nStatute: Crimes Act 1961, s 231",
        "executive_summary": "The prosecution case depends on identification evidence.",
        "charge_and_legislative_framework": "Charge: Burglary\nStatute: Crimes Act 1961, s 231",
        "summary_of_evidence": "1. CCTV footage shows an individual entering the store.\n2. A witness statement describes the suspect.",
        "assessment_of_prosecution_case": "The identification evidence is weak.",
        "evidence_analysis": "CCTV quality is poor and the witness view was brief.",
        "elements_of_the_offence": "1. The defendant entered a building as a trespasser.\n2. The defendant intended to commit a crime inside.",
        "defence_strategies": "Strategy Name: Challenge identification\n**Objective:** Undermine the reliability of the CCTV evidence.",
        "cross_examination_priorities": "1. Confirm the camera angle and lighting conditions.\n2. Establish how long the witness observed the suspect.",
        "disclosure_and_forensic_gaps": "- Chain-of-custody records for seized exhibits\n- Original unedited CCTV footage",
        "instructions_to_counsel_pre_trial": "Obtain the original CCTV footage.",
        "evidentiary_issues_to_raise": "Legal Basis: Evidence Act 2006, s 23\nReliability of the alleged identification.",
        "conclusion": "The defence has a realistic prospect of acquittal.",
        "disclaimer": "This analysis is generated by AI and does not constitute legal advice.",
        "success": True,
    }


def test_build_docx_creates_valid_buffer():
    buf = build_docx(_sample_result())
    assert isinstance(buf, BytesIO)
    data = buf.getvalue()
    assert data.startswith(b"PK")
    assert len(data) > 1000


def test_build_docx_contains_all_main_sections():
    from docx import Document

    buf = build_docx(_sample_result())
    doc = Document(buf)
    full_text = "\n".join(p.text for p in doc.paragraphs)
    expected_headings = [
        "1. EXECUTIVE SUMMARY",
        "2. CHARGE AND LEGISLATIVE FRAMEWORK",
        "3. SUMMARY OF EVIDENCE",
        "4. ASSESSMENT OF PROSECUTION CASE",
        "5. EVIDENCE ANALYSIS",
        "6. ELEMENTS THE PROSECUTION MUST PROVE",
        "7. DEFENCE STRATEGIES AND OPTIONS",
        "8. CROSS-EXAMINATION PRIORITIES",
        "9. DISCLOSURE AND FORENSIC GAPS",
        "10. INSTRUCTIONS TO COUNSEL PRE-TRIAL",
        "11. EVIDENTIARY ISSUES TO RAISE",
        "12. CONCLUSION",
    ]
    for heading in expected_headings:
        assert heading in full_text, f"Missing heading: {heading}"


def test_build_html_contains_brand_and_sections():
    html = build_html(_sample_result())
    assert "AEGIS" in html
    assert "EXECUTIVE SUMMARY" in html
    assert "CROSS-EXAMINATION PRIORITIES" in html
    assert "DISCLOSURE AND FORENSIC GAPS" in html
    assert "EVIDENCE ANALYSIS" in html


def test_build_pdf_falls_back_to_fpdf(monkeypatch):
    """When docx2pdf is unavailable, build_pdf must return a valid PDF buffer."""
    import sys
    import core.report_export as re_mod

    # Make docx2pdf unimportable for the duration of the call.
    monkeypatch.setitem(sys.modules, "docx2pdf", None)
    # In case the module was previously imported, remove the cached reference.
    monkeypatch.setattr(re_mod, "convert", None, raising=False)

    buf = build_pdf(_sample_result())
    assert isinstance(buf, BytesIO)
    data = buf.getvalue()
    assert data.startswith(b"%PDF")
    assert len(data) > 1000
